# Generated by Django 4.1.7 on 2023-02-19 19:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=30, verbose_name='страна')),
                ('city', models.CharField(max_length=30, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('home_number', models.PositiveIntegerField(verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100, unique=True, verbose_name='название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='модель продукта')),
                ('date_release', models.DateField(default=django.utils.datetime_safe.date.today, verbose_name='дата релиза продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_link', models.PositiveSmallIntegerField(choices=[(1, 'завод'), (2, 'розничная сеть'), (3, 'индивидуальный предприниматель')], verbose_name='звено цепи')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название фирмы')),
                ('providers', models.CharField(blank=True, max_length=30, verbose_name='поставщик')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='задолженность перед поставщиком')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_info.contacts', verbose_name='контакты')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_info.products', verbose_name='продукты')),
            ],
            options={
                'verbose_name': 'сеть по продаже',
                'verbose_name_plural': 'сети продаж',
            },
        ),
    ]
